package Letter.Management;

import static Letter.Management.ClerkLogin.setUIFont;
import java.awt.Dimension;
import java.awt.Font;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Lenovo
 */
public class ClerkAddLetter extends javax.swing.JFrame {

    /**
     * Creates new form ClerkAddLetter
     */
    public ClerkAddLetter() {
        initComponents();
        initFrame();
        initFromNameComboBox();
        initToBranchComboBox();
        initShowRegister();
        
        AutoCompleteDecorator.decorate(FromNameComboBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        HeadingPanel = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        AddLetterPanel = new javax.swing.JPanel();
        AddLetterFormPanel = new javax.swing.JPanel();
        InwardRegisterNumberPanel = new javax.swing.JPanel();
        InwardRegisterNoLabel = new javax.swing.JLabel();
        InwardRegsiterNumberField = new javax.swing.JLabel();
        FromPanel = new javax.swing.JPanel();
        FromLetterNoLabel = new javax.swing.JLabel();
        FromLetterNoField = new javax.swing.JTextField();
        FromDateLabel = new javax.swing.JLabel();
        FromDateField = new javax.swing.JTextField();
        FromNameLabel = new javax.swing.JLabel();
        DateSentShowTodayButton = new javax.swing.JButton();
        FromNameComboBox = new javax.swing.JComboBox<>();
        FromNameField = new javax.swing.JTextField();
        ToDateReceivedLabel2 = new javax.swing.JLabel();
        SubjectPanel = new javax.swing.JPanel();
        SubjectLabel = new javax.swing.JLabel();
        SubjectField = new javax.swing.JTextField();
        ToPanel = new javax.swing.JPanel();
        ToNameLabel = new javax.swing.JLabel();
        ToBranchLabel = new javax.swing.JLabel();
        ToDateReceivedLabel = new javax.swing.JLabel();
        ToDateReceivedField = new javax.swing.JTextField();
        DateReceivedShowTodayButton = new javax.swing.JButton();
        ToDateReceivedLabel1 = new javax.swing.JLabel();
        ToBranchComboBox = new javax.swing.JComboBox<>();
        ToNameComboBox = new javax.swing.JComboBox<>();
        ActionButtonsPanel = new javax.swing.JPanel();
        SignoutButton = new javax.swing.JButton();
        AddLetterButton = new javax.swing.JButton();
        ShowRegisterButton = new javax.swing.JButton();
        EmployeeStatsButton = new javax.swing.JButton();
        ShowButton = new javax.swing.JButton();
        ShowRegisterPanel = new javax.swing.JPanel();
        ShowRegisterSortByComboBox = new javax.swing.JComboBox<>();
        EmployeeStatsOptions = new javax.swing.JPanel();
        NameEmployeeStatsComboBox = new javax.swing.JComboBox<>();
        BranchEmployeeStatsComboBox = new javax.swing.JComboBox<>();
        SortByEmployeeStatsComboBox = new javax.swing.JComboBox<>();
        EmployeeStatsFilterPeriodPanel = new javax.swing.JPanel();
        FromPeriodField = new javax.swing.JTextField();
        ToPeriodField = new javax.swing.JTextField();
        ToPeriodLabel = new javax.swing.JLabel();
        TablePanel = new javax.swing.JPanel();
        TablesPane = new javax.swing.JTabbedPane();
        ShowDirectoryScrollPane = new javax.swing.JScrollPane();
        ShowRegisterTable = new javax.swing.JTable();
        EmployeeStatsPane = new javax.swing.JPanel();
        EmployeeStatsScrollPane = new javax.swing.JScrollPane();
        EmployeeStatsTable = new javax.swing.JTable();
        TasksScrollPane = new javax.swing.JScrollPane();
        TasksTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 640));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setName("Clerk Home"); // NOI18N
        setSize(new java.awt.Dimension(1000, 640));

        HeaderPanel.setBackground(new java.awt.Color(225, 250, 225));
        HeaderPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        HeadingPanel.setBackground(new java.awt.Color(147, 217, 163));
        HeadingPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HeadingLabel.setBackground(new java.awt.Color(147, 217, 163));
        HeadingLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        HeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadingLabel.setText("INWARD REGISTER");

        javax.swing.GroupLayout HeadingPanelLayout = new javax.swing.GroupLayout(HeadingPanel);
        HeadingPanel.setLayout(HeadingPanelLayout);
        HeadingPanelLayout.setHorizontalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeadingPanelLayout.setVerticalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadingPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(HeadingLabel)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(HeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        AddLetterPanel.setBackground(new java.awt.Color(225, 250, 225));
        AddLetterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        InwardRegisterNumberPanel.setBackground(new java.awt.Color(147, 217, 163));
        InwardRegisterNumberPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        InwardRegisterNoLabel.setBackground(new java.awt.Color(102, 255, 102));
        InwardRegisterNoLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        InwardRegisterNoLabel.setText("Inward Register Number ");

        InwardRegsiterNumberField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        InwardRegsiterNumberField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InwardRegsiterNumberField.setText("00");
        InwardRegsiterNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout InwardRegisterNumberPanelLayout = new javax.swing.GroupLayout(InwardRegisterNumberPanel);
        InwardRegisterNumberPanel.setLayout(InwardRegisterNumberPanelLayout);
        InwardRegisterNumberPanelLayout.setHorizontalGroup(
            InwardRegisterNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InwardRegisterNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InwardRegisterNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InwardRegsiterNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InwardRegisterNumberPanelLayout.setVerticalGroup(
            InwardRegisterNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InwardRegisterNumberPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(InwardRegisterNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InwardRegisterNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InwardRegsiterNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        FromPanel.setBackground(new java.awt.Color(147, 217, 163));
        FromPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FromLetterNoLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromLetterNoLabel.setText("Number");
        FromLetterNoLabel.setToolTipText("From Number");
        FromLetterNoLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        FromLetterNoLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        FromLetterNoLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        FromLetterNoField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromLetterNoField.setText("Number");
        FromLetterNoField.setToolTipText("From Number");
        FromLetterNoField.setMinimumSize(new java.awt.Dimension(150, 30));
        FromLetterNoField.setPreferredSize(new java.awt.Dimension(150, 30));

        FromDateLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromDateLabel.setText("Date Sent");
        FromDateLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        FromDateLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        FromDateLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        FromDateField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromDateField.setMinimumSize(new java.awt.Dimension(150, 30));
        FromDateField.setPreferredSize(new java.awt.Dimension(150, 30));

        FromNameLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromNameLabel.setText("Name");
        FromNameLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        FromNameLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        FromNameLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        DateSentShowTodayButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        DateSentShowTodayButton.setText("Today");
        DateSentShowTodayButton.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        DateSentShowTodayButton.setMinimumSize(new java.awt.Dimension(80, 34));
        DateSentShowTodayButton.setPreferredSize(new java.awt.Dimension(80, 34));
        DateSentShowTodayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateSentShowTodayButtonActionPerformed(evt);
            }
        });

        FromNameComboBox.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Name" }));
        FromNameComboBox.setMinimumSize(new java.awt.Dimension(196, 32));
        FromNameComboBox.setNextFocusableComponent(SubjectField);
        FromNameComboBox.setPreferredSize(new java.awt.Dimension(196, 32));
        FromNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromNameComboBoxActionPerformed(evt);
            }
        });

        FromNameField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromNameField.setDragEnabled(true);
        FromNameField.setMargin(new java.awt.Insets(1, 1, 1, 1));
        FromNameField.setMinimumSize(new java.awt.Dimension(196, 34));
        FromNameField.setNextFocusableComponent(SubjectField);
        FromNameField.setPreferredSize(new java.awt.Dimension(196, 34));

        ToDateReceivedLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToDateReceivedLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ToDateReceivedLabel2.setText("FROM");
        ToDateReceivedLabel2.setMaximumSize(new java.awt.Dimension(100, 262626));
        ToDateReceivedLabel2.setMinimumSize(new java.awt.Dimension(100, 30));
        ToDateReceivedLabel2.setPreferredSize(new java.awt.Dimension(110, 30));

        javax.swing.GroupLayout FromPanelLayout = new javax.swing.GroupLayout(FromPanel);
        FromPanel.setLayout(FromPanelLayout);
        FromPanelLayout.setHorizontalGroup(
            FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FromPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToDateReceivedLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FromDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(FromLetterNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FromLetterNoField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FromDateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FromNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FromPanelLayout.createSequentialGroup()
                        .addComponent(DateSentShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(FromNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
        );
        FromPanelLayout.setVerticalGroup(
            FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FromPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ToDateReceivedLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FromPanelLayout.createSequentialGroup()
                        .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FromLetterNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromLetterNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FromDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateSentShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FromNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        SubjectPanel.setBackground(new java.awt.Color(147, 217, 163));
        SubjectPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SubjectPanel.setMinimumSize(new java.awt.Dimension(340, 48));
        SubjectPanel.setPreferredSize(new java.awt.Dimension(340, 48));

        SubjectLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        SubjectLabel.setText("Subject");

        SubjectField.setNextFocusableComponent(ToDateReceivedField);

        javax.swing.GroupLayout SubjectPanelLayout = new javax.swing.GroupLayout(SubjectPanel);
        SubjectPanel.setLayout(SubjectPanelLayout);
        SubjectPanelLayout.setHorizontalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(SubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SubjectPanelLayout.setVerticalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubjectPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ToPanel.setBackground(new java.awt.Color(147, 217, 163));
        ToPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ToNameLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToNameLabel.setText("Name");
        ToNameLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        ToNameLabel.setPreferredSize(new java.awt.Dimension(110, 30));

        ToBranchLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToBranchLabel.setText("Branch");
        ToBranchLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        ToBranchLabel.setPreferredSize(new java.awt.Dimension(110, 30));

        ToDateReceivedLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToDateReceivedLabel.setText("Date Received");
        ToDateReceivedLabel.setMaximumSize(new java.awt.Dimension(100, 262626));
        ToDateReceivedLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        ToDateReceivedLabel.setPreferredSize(new java.awt.Dimension(110, 30));

        ToDateReceivedField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToDateReceivedField.setMinimumSize(new java.awt.Dimension(150, 30));
        ToDateReceivedField.setName(""); // NOI18N
        ToDateReceivedField.setPreferredSize(new java.awt.Dimension(150, 30));

        DateReceivedShowTodayButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        DateReceivedShowTodayButton.setText("Today");
        DateReceivedShowTodayButton.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        DateReceivedShowTodayButton.setMinimumSize(new java.awt.Dimension(100, 30));
        DateReceivedShowTodayButton.setPreferredSize(new java.awt.Dimension(100, 30));
        DateReceivedShowTodayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateReceivedShowTodayButtonActionPerformed(evt);
            }
        });

        ToDateReceivedLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToDateReceivedLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ToDateReceivedLabel1.setText("TO");
        ToDateReceivedLabel1.setMaximumSize(new java.awt.Dimension(100, 262626));
        ToDateReceivedLabel1.setMinimumSize(new java.awt.Dimension(100, 30));
        ToDateReceivedLabel1.setPreferredSize(new java.awt.Dimension(110, 30));

        ToBranchComboBox.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToBranchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Branch" }));
        ToBranchComboBox.setMinimumSize(new java.awt.Dimension(196, 32));
        ToBranchComboBox.setPreferredSize(new java.awt.Dimension(196, 32));
        ToBranchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBranchComboBoxActionPerformed(evt);
            }
        });

        ToNameComboBox.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Name" }));
        ToNameComboBox.setMinimumSize(new java.awt.Dimension(196, 32));
        ToNameComboBox.setPreferredSize(new java.awt.Dimension(196, 32));

        javax.swing.GroupLayout ToPanelLayout = new javax.swing.GroupLayout(ToPanel);
        ToPanel.setLayout(ToPanelLayout);
        ToPanelLayout.setHorizontalGroup(
            ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToDateReceivedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ToNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToDateReceivedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToBranchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ToPanelLayout.createSequentialGroup()
                        .addComponent(ToDateReceivedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateReceivedShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ToBranchComboBox, 0, 1, Short.MAX_VALUE)
                    .addComponent(ToNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        ToPanelLayout.setVerticalGroup(
            ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ToPanelLayout.createSequentialGroup()
                        .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ToDateReceivedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToDateReceivedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateReceivedShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToBranchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToBranchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ToDateReceivedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout AddLetterFormPanelLayout = new javax.swing.GroupLayout(AddLetterFormPanel);
        AddLetterFormPanel.setLayout(AddLetterFormPanelLayout);
        AddLetterFormPanelLayout.setHorizontalGroup(
            AddLetterFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLetterFormPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(AddLetterFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SubjectPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addComponent(InwardRegisterNumberPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FromPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        AddLetterFormPanelLayout.setVerticalGroup(
            AddLetterFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLetterFormPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(InwardRegisterNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FromPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SubjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ToPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        ActionButtonsPanel.setBackground(new java.awt.Color(225, 250, 225));

        SignoutButton.setBackground(new java.awt.Color(255, 102, 102));
        SignoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-src/logout24.png"))); // NOI18N
        SignoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoutButtonActionPerformed(evt);
            }
        });

        AddLetterButton.setBackground(new java.awt.Color(102, 255, 102));
        AddLetterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-src/Add24.png"))); // NOI18N
        AddLetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLetterButtonActionPerformed(evt);
            }
        });

        ShowRegisterButton.setBackground(new java.awt.Color(204, 204, 204));
        ShowRegisterButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ShowRegisterButton.setText("Show Register");
        ShowRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRegisterButtonActionPerformed(evt);
            }
        });

        EmployeeStatsButton.setBackground(new java.awt.Color(204, 204, 204));
        EmployeeStatsButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        EmployeeStatsButton.setText("Employee Stats");
        EmployeeStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeStatsButtonActionPerformed(evt);
            }
        });

        ShowButton.setBackground(new java.awt.Color(255, 255, 255));
        ShowButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ShowButton.setText("Show");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionButtonsPanelLayout = new javax.swing.GroupLayout(ActionButtonsPanel);
        ActionButtonsPanel.setLayout(ActionButtonsPanelLayout);
        ActionButtonsPanelLayout.setHorizontalGroup(
            ActionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionButtonsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SignoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddLetterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowRegisterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmployeeStatsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        ActionButtonsPanelLayout.setVerticalGroup(
            ActionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionButtonsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(ActionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowRegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddLetterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        ShowRegisterPanel.setBackground(new java.awt.Color(225, 250, 225));

        ShowRegisterSortByComboBox.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ShowRegisterSortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort By", "" }));
        ShowRegisterSortByComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRegisterSortByComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShowRegisterPanelLayout = new javax.swing.GroupLayout(ShowRegisterPanel);
        ShowRegisterPanel.setLayout(ShowRegisterPanelLayout);
        ShowRegisterPanelLayout.setHorizontalGroup(
            ShowRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowRegisterPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ShowRegisterSortByComboBox, 0, 201, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        ShowRegisterPanelLayout.setVerticalGroup(
            ShowRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowRegisterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowRegisterSortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EmployeeStatsOptions.setBackground(new java.awt.Color(225, 250, 225));

        NameEmployeeStatsComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        NameEmployeeStatsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Name" }));
        NameEmployeeStatsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NameEmployeeStatsComboBoxItemStateChanged(evt);
            }
        });
        NameEmployeeStatsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameEmployeeStatsComboBoxActionPerformed(evt);
            }
        });

        BranchEmployeeStatsComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BranchEmployeeStatsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Branch" }));
        BranchEmployeeStatsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchEmployeeStatsComboBoxActionPerformed(evt);
            }
        });

        SortByEmployeeStatsComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SortByEmployeeStatsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Period", "Last Week", "Last Month", "Last Year" }));
        SortByEmployeeStatsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortByEmployeeStatsComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeStatsOptionsLayout = new javax.swing.GroupLayout(EmployeeStatsOptions);
        EmployeeStatsOptions.setLayout(EmployeeStatsOptionsLayout);
        EmployeeStatsOptionsLayout.setHorizontalGroup(
            EmployeeStatsOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeStatsOptionsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(EmployeeStatsOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SortByEmployeeStatsComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BranchEmployeeStatsComboBox, 0, 250, Short.MAX_VALUE)
                    .addComponent(NameEmployeeStatsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        EmployeeStatsOptionsLayout.setVerticalGroup(
            EmployeeStatsOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeStatsOptionsLayout.createSequentialGroup()
                .addComponent(BranchEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SortByEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EmployeeStatsFilterPeriodPanel.setBackground(new java.awt.Color(225, 250, 225));

        FromPeriodField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        FromPeriodField.setMinimumSize(new java.awt.Dimension(110, 30));
        FromPeriodField.setPreferredSize(new java.awt.Dimension(110, 30));

        ToPeriodField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ToPeriodField.setMinimumSize(new java.awt.Dimension(110, 30));
        ToPeriodField.setPreferredSize(new java.awt.Dimension(110, 30));

        ToPeriodLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ToPeriodLabel.setText("--");

        javax.swing.GroupLayout EmployeeStatsFilterPeriodPanelLayout = new javax.swing.GroupLayout(EmployeeStatsFilterPeriodPanel);
        EmployeeStatsFilterPeriodPanel.setLayout(EmployeeStatsFilterPeriodPanelLayout);
        EmployeeStatsFilterPeriodPanelLayout.setHorizontalGroup(
            EmployeeStatsFilterPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeStatsFilterPeriodPanelLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(FromPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToPeriodLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EmployeeStatsFilterPeriodPanelLayout.setVerticalGroup(
            EmployeeStatsFilterPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeStatsFilterPeriodPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(EmployeeStatsFilterPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToPeriodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout AddLetterPanelLayout = new javax.swing.GroupLayout(AddLetterPanel);
        AddLetterPanel.setLayout(AddLetterPanelLayout);
        AddLetterPanelLayout.setHorizontalGroup(
            AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLetterPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddLetterPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddLetterFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLetterPanelLayout.createSequentialGroup()
                        .addComponent(ShowRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmployeeStatsOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmployeeStatsFilterPeriodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ActionButtonsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        AddLetterPanelLayout.setVerticalGroup(
            AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLetterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddLetterFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActionButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeStatsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeStatsFilterPeriodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablePanel.setBackground(new java.awt.Color(225, 250, 225));
        TablePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablesPane.setBackground(new java.awt.Color(147, 217, 163));
        TablesPane.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        TablesPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablesPane.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TablesPane.setOpaque(true);

        ShowRegisterTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ShowRegisterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Inward Register", "Worksheet No", "From - Number", "From - Date", "From - Name", "Subject", "To - Date", "To - Branch", "To - Name", "Out Date", "Remark", "Progress"
            }
        ));
        ShowRegisterTable.setFillsViewportHeight(true);
        ShowRegisterTable.setInheritsPopupMenu(true);
        ShowRegisterTable.setNextFocusableComponent(SubjectField);
        ShowRegisterTable.setRowHeight(25);
        ShowRegisterTable.setShowGrid(true);
        ShowRegisterTable.getTableHeader().setReorderingAllowed(false);
        ShowRegisterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowRegisterTableMouseClicked(evt);
            }
        });
        ShowDirectoryScrollPane.setViewportView(ShowRegisterTable);

        TablesPane.addTab("Show Register", ShowDirectoryScrollPane);

        EmployeeStatsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        EmployeeStatsTable.setRowHeight(25);
        EmployeeStatsScrollPane.setViewportView(EmployeeStatsTable);

        TasksTable.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        TasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Email", "Pending Letters", "Completed Letters", "Total Letters"
            }
        ));
        TasksTable.setRowHeight(25);
        TasksScrollPane.setViewportView(TasksTable);

        javax.swing.GroupLayout EmployeeStatsPaneLayout = new javax.swing.GroupLayout(EmployeeStatsPane);
        EmployeeStatsPane.setLayout(EmployeeStatsPaneLayout);
        EmployeeStatsPaneLayout.setHorizontalGroup(
            EmployeeStatsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeStatsPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(EmployeeStatsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeStatsScrollPane)
                    .addComponent(TasksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        EmployeeStatsPaneLayout.setVerticalGroup(
            EmployeeStatsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeStatsPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(EmployeeStatsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TasksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        TablesPane.addTab("Employee Stats", EmployeeStatsPane);

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TablesPane)
                .addGap(30, 30, 30))
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TablesPane)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddLetterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddLetterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddLetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLetterButtonActionPerformed
        // TODO add your handling code here:
        
        String InwardRegisterNo = InwardRegsiterNumberField.getText();
        
        String FromLetterNo = FromLetterNoField.getText();
        String FromDate = FromDateField.getText();
        String FromName;
        if (FromNameComboBox.getSelectedItem() == "Other") {
            FromName = FromNameField.getText();
        }
        else {
            FromName = FromNameComboBox.getSelectedItem().toString();
        }
        
        String Subject = SubjectField.getText();
        
        String ToDateReceived = ToDateReceivedField.getText();
        String ToBranch = ToBranchComboBox.getSelectedItem().toString();
        String ToName = ToNameComboBox.getSelectedItem().toString();
        
        String EmpID = getEmployeeID();
        String Progress = "Added";
        
        try {
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "INSERT INTO letterinwardregister"
                        + "(InwardNo, "
                        + "FromNo, FromDateSent, FromName, "
                        + "Subject, "
                        + "ToDateReceived, ToBranch, ToName, "
                        + "EmpID, Progress) "
                        + "values(?, ?, STR_TO_DATE(?,'%d-%m-%Y'), ?, ?, STR_TO_DATE(?,'%d-%m-%Y'), ?, ?, ?, ?)";
                        PreparedStatement st = con.c.prepareStatement(sql);
                        
                        st.setString(1, InwardRegisterNo);
                        st.setString(2, FromLetterNo);
                        st.setString(3, FromDate);
                        st.setString(4, FromName);
                        st.setString(5, Subject);
                        st.setString(6, ToDateReceived);
                        st.setString(7, ToBranch);
                        st.setString(8, ToName);
                        st.setString(9, EmpID);
                        st.setString(10, Progress);
                        
                        
                        
                        int i = st.executeUpdate();
                        if (i > 0){
                            JOptionPane.showMessageDialog(null, "Successfully Created");
                        }
            
                        
            String sqlPending= "UPDATE letteremployee "
                        + "SET Pending = Pending + 1,"
                        + "Total = Total + 1 "
                        + "WHERE ID='"+EmpID+"'";
                        PreparedStatement stPending = con.c.prepareStatement(sqlPending);
                        stPending.executeUpdate();

            this.setVisible(false);
            new ClerkAddLetter().setVisible(true);
                        
        } catch(SQLException esql){
            esql.printStackTrace();
            JOptionPane.showMessageDialog(null, "Please Enter Inward Register Number.");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddLetterButtonActionPerformed

    private void ShowRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRegisterButtonActionPerformed
        // TODO add your handling code here:
        TablesPane.setSelectedIndex(0);
        EmployeeStatsOptions.setVisible(false);
        EmployeeStatsFilterPeriodPanel.setVisible(false);
        ShowRegisterPanel.setVisible(true);
    }//GEN-LAST:event_ShowRegisterButtonActionPerformed

    private void SignoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoutButtonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Are you sure?","Sign Out",JOptionPane.YES_NO_OPTION);  
        if(a == JOptionPane.YES_OPTION){  
            this.setVisible(false);
            new ClerkLogin().setVisible(true); 
        }  
    }//GEN-LAST:event_SignoutButtonActionPerformed

    private void EmployeeStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeStatsButtonActionPerformed
        // TODO add your handling code here:
        TablesPane.setSelectedIndex(1);
        ShowRegisterPanel.setVisible(false);
        EmployeeStatsOptions.setVisible(true);
        EmployeeStatsFilterPeriodPanel.setVisible(true);
//        initPeriod();
    }//GEN-LAST:event_EmployeeStatsButtonActionPerformed

    private void FromNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromNameComboBoxActionPerformed
        // TODO add your handling code here:
        System.out.println(FromNameComboBox.getSelectedItem());
        if (FromNameComboBox.getSelectedItem().equals("Other") && FromNameField.isVisible() == false) {
            FromNameField.setVisible(true);
//            FromNameComboBoxFocusLost(evt);
        }
        else {
            FromNameField.setVisible(false);
        }
        
    }//GEN-LAST:event_FromNameComboBoxActionPerformed

    private void DateSentShowTodayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateSentShowTodayButtonActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String date = LocalDate.now().format(formatter);
        
        FromDateField.setText(date);
    }//GEN-LAST:event_DateSentShowTodayButtonActionPerformed

    private void ToBranchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBranchComboBoxActionPerformed
        // TODO add your handling code here:
        initToNameComboBox();
    }//GEN-LAST:event_ToBranchComboBoxActionPerformed

    private void DateReceivedShowTodayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateReceivedShowTodayButtonActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String date = LocalDate.now().format(formatter);
        
        ToDateReceivedField.setText(date);
    }//GEN-LAST:event_DateReceivedShowTodayButtonActionPerformed

    private void ShowRegisterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowRegisterTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowRegisterTableMouseClicked

    private void BranchEmployeeStatsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchEmployeeStatsComboBoxActionPerformed
        // TODO add your handling code here:
        initNameEmployeeStatsComboBox();
        
    }//GEN-LAST:event_BranchEmployeeStatsComboBoxActionPerformed

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        // TODO add your handling code here:
        
        if (BranchEmployeeStatsComboBox.getSelectedItem() == "Select Branch") {
            
        }
        else {
            initEmployeeStats();
            initTasks();
        }
        
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void NameEmployeeStatsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NameEmployeeStatsComboBoxItemStateChanged
        // TODO add your handling code here:
//        initEmployeeStats();
//        initTasks();
    }//GEN-LAST:event_NameEmployeeStatsComboBoxItemStateChanged

    private void SortByEmployeeStatsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortByEmployeeStatsComboBoxActionPerformed
        // TODO add your handling code here:
        String period = SortByEmployeeStatsComboBox.getSelectedItem().toString();
        
        if (period.equals("Last Week")) {
            DefaultTableModel EmployeeStatsTableModel  = new DefaultTableModel();
            EmployeeStatsTable.setModel(EmployeeStatsTableModel);
            EmployeeStatsTableModel.addColumn("Inward No");
            EmployeeStatsTableModel.addColumn("Worksheet");        
            EmployeeStatsTableModel.addColumn("From No");
            EmployeeStatsTableModel.addColumn("From Date");
            EmployeeStatsTableModel.addColumn("From Name");
            EmployeeStatsTableModel.addColumn("Subject");
            EmployeeStatsTableModel.addColumn("To Date");
            EmployeeStatsTableModel.addColumn("Out Date");
            EmployeeStatsTableModel.addColumn("Remark");
            EmployeeStatsTableModel.addColumn("Progress");
    //        EmployeeStatsTableModel.addColumn("Days");

            ShowRegisterTable.getTableHeader().setPreferredSize(
                new Dimension(ShowRegisterTable.getColumnModel().getTotalColumnWidth(), 28));

            String branch = BranchEmployeeStatsComboBox.getSelectedItem().toString();
            String toName = NameEmployeeStatsComboBox.getSelectedItem().toString();

            try {


                ConnectionEstablish con = new ConnectionEstablish();
                String sql = "SELECT * FROM letterinwardregister "
                        + "WHERE ToBranch = '"+branch+"' AND "
                        + "ToName = '"+toName+"' AND "
                        + "ToDateReceived> now() -  interval 7 day";
                PreparedStatement st = con.c.prepareStatement(sql);
                ResultSet rs = st.executeQuery();

                while(rs.next()) {
                    String InwardNo = rs.getString("InwardNo");
                    String WorksheetNo = rs.getString("WorksheetNo");
                    String FromNo = rs.getString("FromNo");
                    String FromDateSent = rs.getString("FromDateSent");
                    String FromName = rs.getString("FromName");
                    String Subject = rs.getString("Subject");
                    String ToDateReceived = rs.getString("ToDateReceived");
                    String OutDate = rs.getString("OutDate");
                    String Remark = rs.getString("Remark");
                    String Progress = rs.getString("Progress");
    //                String Days = rs.getString("Days");

                    String tableData[] = {InwardNo, WorksheetNo, FromNo, FromDateSent, FromName, 
                        Subject, ToDateReceived, OutDate, Remark, Progress};

                    EmployeeStatsTableModel.addRow(tableData);
                }
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
        else if (period.equals("Last Month")) {
            DefaultTableModel EmployeeStatsTableModel  = new DefaultTableModel();
            EmployeeStatsTable.setModel(EmployeeStatsTableModel);
            EmployeeStatsTableModel.addColumn("Inward No");
            EmployeeStatsTableModel.addColumn("Worksheet");        
            EmployeeStatsTableModel.addColumn("From No");
            EmployeeStatsTableModel.addColumn("From Date");
            EmployeeStatsTableModel.addColumn("From Name");
            EmployeeStatsTableModel.addColumn("Subject");
            EmployeeStatsTableModel.addColumn("To Date");
            EmployeeStatsTableModel.addColumn("Out Date");
            EmployeeStatsTableModel.addColumn("Remark");
            EmployeeStatsTableModel.addColumn("Progress");
    //        EmployeeStatsTableModel.addColumn("Days");

            ShowRegisterTable.getTableHeader().setPreferredSize(
                new Dimension(ShowRegisterTable.getColumnModel().getTotalColumnWidth(), 28));

            String branch = BranchEmployeeStatsComboBox.getSelectedItem().toString();
            String toName = NameEmployeeStatsComboBox.getSelectedItem().toString();

            try {


                ConnectionEstablish con = new ConnectionEstablish();
                String sql = "SELECT * FROM letterinwardregister "
                        + "WHERE ToBranch = '"+branch+"' AND "
                        + "ToName = '"+toName+"' AND "
                        + "ToDateReceived> now() -  interval 31 day";
                PreparedStatement st = con.c.prepareStatement(sql);
                ResultSet rs = st.executeQuery();

                while(rs.next()) {
                    String InwardNo = rs.getString("InwardNo");
                    String WorksheetNo = rs.getString("WorksheetNo");
                    String FromNo = rs.getString("FromNo");
                    String FromDateSent = rs.getString("FromDateSent");
                    String FromName = rs.getString("FromName");
                    String Subject = rs.getString("Subject");
                    String ToDateReceived = rs.getString("ToDateReceived");
                    String OutDate = rs.getString("OutDate");
                    String Remark = rs.getString("Remark");
                    String Progress = rs.getString("Progress");
    //                String Days = rs.getString("Days");

                    String tableData[] = {InwardNo, WorksheetNo, FromNo, FromDateSent, FromName, 
                        Subject, ToDateReceived, OutDate, Remark, Progress};

                    EmployeeStatsTableModel.addRow(tableData);
                }
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
        else if (period.equals("Last Year")) {
            DefaultTableModel EmployeeStatsTableModel  = new DefaultTableModel();
            EmployeeStatsTable.setModel(EmployeeStatsTableModel);
            EmployeeStatsTableModel.addColumn("Inward No");
            EmployeeStatsTableModel.addColumn("Worksheet");        
            EmployeeStatsTableModel.addColumn("From No");
            EmployeeStatsTableModel.addColumn("From Date");
            EmployeeStatsTableModel.addColumn("From Name");
            EmployeeStatsTableModel.addColumn("Subject");
            EmployeeStatsTableModel.addColumn("To Date");
            EmployeeStatsTableModel.addColumn("Out Date");
            EmployeeStatsTableModel.addColumn("Remark");
            EmployeeStatsTableModel.addColumn("Progress");
    //        EmployeeStatsTableModel.addColumn("Days");

            ShowRegisterTable.getTableHeader().setPreferredSize(
                new Dimension(ShowRegisterTable.getColumnModel().getTotalColumnWidth(), 28));

            String branch = BranchEmployeeStatsComboBox.getSelectedItem().toString();
            String toName = NameEmployeeStatsComboBox.getSelectedItem().toString();

            try {


                ConnectionEstablish con = new ConnectionEstablish();
                String sql = "SELECT * FROM letterinwardregister "
                        + "WHERE ToBranch = '"+branch+"' AND "
                        + "ToName = '"+toName+"' AND "
                        + "ToDateReceived> now() -  interval 365 day";
                PreparedStatement st = con.c.prepareStatement(sql);
                ResultSet rs = st.executeQuery();

                while(rs.next()) {
                    String InwardNo = rs.getString("InwardNo");
                    String WorksheetNo = rs.getString("WorksheetNo");
                    String FromNo = rs.getString("FromNo");
                    String FromDateSent = rs.getString("FromDateSent");
                    String FromName = rs.getString("FromName");
                    String Subject = rs.getString("Subject");
                    String ToDateReceived = rs.getString("ToDateReceived");
                    String OutDate = rs.getString("OutDate");
                    String Remark = rs.getString("Remark");
                    String Progress = rs.getString("Progress");
    //                String Days = rs.getString("Days");

                    String tableData[] = {InwardNo, WorksheetNo, FromNo, FromDateSent, FromName, 
                        Subject, ToDateReceived, OutDate, Remark, Progress};

                    EmployeeStatsTableModel.addRow(tableData);
                }
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_SortByEmployeeStatsComboBoxActionPerformed

    private void NameEmployeeStatsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameEmployeeStatsComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NameEmployeeStatsComboBoxActionPerformed

    private void ShowRegisterSortByComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRegisterSortByComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ShowRegisterSortByComboBoxActionPerformed
    
    private String getEmployeeID(){
        
        String branch = ToBranchComboBox.getSelectedItem().toString();
        String name = ToNameComboBox.getSelectedItem().toString();
        try{
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "SELECT ID FROM letteremployee WHERE "
                        + "Branch='"+branch+"' AND Name='"+name+"';";
            PreparedStatement st = con.c.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                String EmpID = rs.getString("ID");
                return EmpID;
            }
            
        } catch (Exception e){
            e.printStackTrace();
        }
        return "null";
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    private void initFrame() {
        setExtendedState(MAXIMIZED_BOTH);
        setUIFont (new javax.swing.plaf.FontUIResource("SansSerif",Font.PLAIN,12));
        
        URL iconURL = getClass().getResource("/img-src/logo.png");
        // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
        setTitle("Water Resources Department, Government of Maharashtra, India");
        
        initInwardRegisterNumber();
        EmployeeStatsOptions.setVisible(false);
        EmployeeStatsFilterPeriodPanel.setVisible(false);
        ShowRegisterPanel.setVisible(false);
                
    }
    
    private void initInwardRegisterNumber() {
        try {
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "SELECT Count(*) FROM letterinwardregister";
            PreparedStatement st = con.c.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while (rs.next()) {
                int no = rs.getInt(1)+1;
                InwardRegsiterNumberField.setText(Integer.toString(no));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void initFromNameComboBox() {

        FromNameField.setVisible(false);
        try {

            // SQL command data stored in String datatype
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "select * from fromtable";
//            String sql = "select * from fromtable ORDER BY FromLetterTotal";
            PreparedStatement st = con.c.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            // Condition check
            while (rs.next()) {
                FromNameComboBox.addItem(rs.getString("Name"));
            }
            FromNameComboBox.addItem("Other");
            
        }   catch (SQLException e) {
            // Print exception pop-up on screen
            System.out.println(e);
            }
    }
    
    private void initToBranchComboBox() {
        
        try {

            // SQL command data stored in String datatype
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "select DISTINCT Branch from letteremployee";
            PreparedStatement st = con.c.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            // Condition check
            while (rs.next()) {
                ToBranchComboBox.addItem(rs.getString("Branch"));
                BranchEmployeeStatsComboBox.addItem(rs.getString("Branch"));
            }
            
        }   catch (SQLException e) {
            // Print exception pop-up on screen
            System.out.println(e);
            }
    }
    
    private void initToNameComboBox() {
        
        ToNameComboBox.removeAllItems();
        ToNameComboBox.addItem("Select Name");
        
        try {

            ConnectionEstablish con = new ConnectionEstablish();
            // SQL command data stored in String datatype
            String sql = "select * from letteremployee WHERE Branch=? ORDER BY Name";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1,(String) ToBranchComboBox.getSelectedItem());
            ResultSet rs = st.executeQuery();
            

            // Condiion check
            while (rs.next()) {
                String name = rs.getString("Name");                
                ToNameComboBox.addItem(name);
            }
            
        }   catch (SQLException e) {
            // Print exception pop-up on screen
            System.out.println(e);
            }
    }
    
    private void initNameEmployeeStatsComboBox() {
        
        NameEmployeeStatsComboBox.removeAllItems();
        NameEmployeeStatsComboBox.addItem("Select Name");
        
        try {

            ConnectionEstablish con = new ConnectionEstablish();
            // SQL command data stored in String datatype
            String sql = "select * from letteremployee WHERE Branch=? ORDER BY Name";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1,(String) BranchEmployeeStatsComboBox.getSelectedItem());
            ResultSet rs = st.executeQuery();
            

            // Condiion check
            while (rs.next()) {
                String name = rs.getString("Name");                
                NameEmployeeStatsComboBox.addItem(name);
            }
            
        }   catch (SQLException e) {
            // Print exception pop-up on screen
            System.out.println(e);
            }
    }
    
    private void initShowRegister() {
        
        DefaultTableModel ShowRegisterTableModel  = new DefaultTableModel();
        ShowRegisterTable.setModel(ShowRegisterTableModel);
        ShowRegisterTableModel.addColumn("No");
        ShowRegisterTableModel.addColumn("Worksheet");
        ShowRegisterTableModel.addColumn("From No");
        ShowRegisterTableModel.addColumn("From Date");
        ShowRegisterTableModel.addColumn("From Name");
        ShowRegisterTableModel.addColumn("Subject");
        ShowRegisterTableModel.addColumn("To Date");
        ShowRegisterTableModel.addColumn("To Branch");
        ShowRegisterTableModel.addColumn("To Name");
        ShowRegisterTableModel.addColumn("Out Date");
        ShowRegisterTableModel.addColumn("Remark");
        ShowRegisterTableModel.addColumn("Progress");
        
        ShowRegisterTable.getTableHeader().setPreferredSize(
            new Dimension(ShowRegisterTable.getColumnModel().getTotalColumnWidth(), 28));
        
        ShowRegisterTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        ShowRegisterTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        
//        DATES
        ShowRegisterTable.getColumnModel().getColumn(3).setPreferredWidth(60);
        ShowRegisterTable.getColumnModel().getColumn(6).setPreferredWidth(60);
        ShowRegisterTable.getColumnModel().getColumn(9).setPreferredWidth(60);
        
        ShowRegisterTable.getColumnModel().getColumn(11).setPreferredWidth(50);
        
        try {
            
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "SELECT *,date_format(FromDateSent,'%d-%m-%y') AS FDS, "
                    + "date_format(ToDateReceived,'%d-%m-%y') AS TDR FROM letterinwardregister";
            PreparedStatement st = con.c.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while(rs.next()) {
                String InwardNo = rs.getString("InwardNo");
                String WorksheetNo = rs.getString("WorksheetNo");
                String FromNo = rs.getString("FromNo");
                String FromDateSent = rs.getString("FDS");
                String FromName = rs.getString("FromName");
                String Subject = rs.getString("Subject");
                String ToDateReceived = rs.getString("TDR");
                String ToBranch = rs.getString("ToBranch");
                String ToName = rs.getString("ToName");
                String OutDate = rs.getString("OutDate");
                String Remark = rs.getString("Remark");
                String Progress = rs.getString("Progress");
                
                String tableData[] = {InwardNo, WorksheetNo, FromNo, FromDateSent, 
                    FromName, Subject, ToDateReceived, ToBranch, ToName, OutDate, Remark, Progress};
            
                ShowRegisterTableModel.addRow(tableData);
                
            }
            
//            ShowRegisterTable.setAutoCreateRowSorter(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void initEmployeeStats() {
        
        DefaultTableModel EmployeeStatsTableModel  = new DefaultTableModel();
        EmployeeStatsTable.setModel(EmployeeStatsTableModel);
        EmployeeStatsTableModel.addColumn("Inward No");
        EmployeeStatsTableModel.addColumn("Worksheet");        
        EmployeeStatsTableModel.addColumn("From No");
        EmployeeStatsTableModel.addColumn("From Date");
        EmployeeStatsTableModel.addColumn("From Name");
        EmployeeStatsTableModel.addColumn("Subject");
        EmployeeStatsTableModel.addColumn("To Date");
        EmployeeStatsTableModel.addColumn("Out Date");
        EmployeeStatsTableModel.addColumn("Remark");
        EmployeeStatsTableModel.addColumn("Progress");
//        EmployeeStatsTableModel.addColumn("Days");
        
        ShowRegisterTable.getTableHeader().setPreferredSize(
            new Dimension(ShowRegisterTable.getColumnModel().getTotalColumnWidth(), 28));
        
        String branch = BranchEmployeeStatsComboBox.getSelectedItem().toString();
        String toName = NameEmployeeStatsComboBox.getSelectedItem().toString();
        
        try {
            
            
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "SELECT * FROM letterinwardregister "
                    + "WHERE ToBranch = '"+branch+"' AND "
                    + "ToName = '"+toName+"'";
            PreparedStatement st = con.c.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while(rs.next()) {
                String InwardNo = rs.getString("InwardNo");
                String WorksheetNo = rs.getString("WorksheetNo");
                String FromNo = rs.getString("FromNo");
                String FromDateSent = rs.getString("FromDateSent");
                String FromName = rs.getString("FromName");
                String Subject = rs.getString("Subject");
                String ToDateReceived = rs.getString("ToDateReceived");
                String OutDate = rs.getString("OutDate");
                String Remark = rs.getString("Remark");
                String Progress = rs.getString("Progress");
//                String Days = rs.getString("Days");
                
                String tableData[] = {InwardNo, WorksheetNo, FromNo, FromDateSent, FromName, 
                    Subject, ToDateReceived, OutDate, Remark, Progress};
            
                EmployeeStatsTableModel.addRow(tableData);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    private void initTasks() {
        
        DefaultTableModel TasksTableModel  = new DefaultTableModel();
        TasksTable.setModel(TasksTableModel);
        TasksTableModel.addColumn("Employee ID");
        TasksTableModel.addColumn("Name");
        TasksTableModel.addColumn("Email");
        TasksTableModel.addColumn("Pending");
        TasksTableModel.addColumn("Completed");
        TasksTableModel.addColumn("Total");
        
        TasksTable.getTableHeader().setPreferredSize(
            new Dimension(TasksTable.getColumnModel().getTotalColumnWidth(), 28));
        
        String branch = BranchEmployeeStatsComboBox.getSelectedItem().toString();
        String toName = NameEmployeeStatsComboBox.getSelectedItem().toString();
        
        try {
            ConnectionEstablish con = new ConnectionEstablish();
            String sql = "SELECT * FROM letteremployee "
                    + "WHERE Branch = '"+branch+"' AND "
                    + "Name = '"+toName+"'";
            PreparedStatement st = con.c.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while(rs.next()) {
                String ID = rs.getString("ID");
                String Name = rs.getString("Name");
                String Email = rs.getString("Email");
                String Pending = rs.getString("Pending");
                String Completed = rs.getString("Completed");
                String Total = rs.getString("Total");
                
                String tableData[] = {ID, Name, Email, Pending, Completed, Total};
            
                TasksTableModel.addRow(tableData);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void initPeriod() {
        SortByEmployeeStatsComboBox.removeAllItems();
        SortByEmployeeStatsComboBox.addItem("'Select Period'");
        SortByEmployeeStatsComboBox.addItem("Last Week");
        SortByEmployeeStatsComboBox.addItem("Last Month");
        SortByEmployeeStatsComboBox.addItem("Last Year");
    }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkAddLetter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionButtonsPanel;
    private javax.swing.JButton AddLetterButton;
    private javax.swing.JPanel AddLetterFormPanel;
    private javax.swing.JPanel AddLetterPanel;
    private javax.swing.JComboBox<String> BranchEmployeeStatsComboBox;
    private javax.swing.JButton DateReceivedShowTodayButton;
    private javax.swing.JButton DateSentShowTodayButton;
    private javax.swing.JButton EmployeeStatsButton;
    private javax.swing.JPanel EmployeeStatsFilterPeriodPanel;
    private javax.swing.JPanel EmployeeStatsOptions;
    private javax.swing.JPanel EmployeeStatsPane;
    private javax.swing.JScrollPane EmployeeStatsScrollPane;
    private javax.swing.JTable EmployeeStatsTable;
    private javax.swing.JTextField FromDateField;
    private javax.swing.JLabel FromDateLabel;
    private javax.swing.JTextField FromLetterNoField;
    private javax.swing.JLabel FromLetterNoLabel;
    private javax.swing.JComboBox<String> FromNameComboBox;
    private javax.swing.JTextField FromNameField;
    private javax.swing.JLabel FromNameLabel;
    private javax.swing.JPanel FromPanel;
    private javax.swing.JTextField FromPeriodField;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JPanel HeadingPanel;
    private javax.swing.JLabel InwardRegisterNoLabel;
    private javax.swing.JPanel InwardRegisterNumberPanel;
    private javax.swing.JLabel InwardRegsiterNumberField;
    private javax.swing.JComboBox<String> NameEmployeeStatsComboBox;
    private javax.swing.JButton ShowButton;
    private javax.swing.JScrollPane ShowDirectoryScrollPane;
    private javax.swing.JButton ShowRegisterButton;
    private javax.swing.JPanel ShowRegisterPanel;
    private javax.swing.JComboBox<String> ShowRegisterSortByComboBox;
    private javax.swing.JTable ShowRegisterTable;
    private javax.swing.JButton SignoutButton;
    private javax.swing.JComboBox<String> SortByEmployeeStatsComboBox;
    private javax.swing.JTextField SubjectField;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JPanel SubjectPanel;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JTabbedPane TablesPane;
    private javax.swing.JScrollPane TasksScrollPane;
    private javax.swing.JTable TasksTable;
    private javax.swing.JComboBox<String> ToBranchComboBox;
    private javax.swing.JLabel ToBranchLabel;
    private javax.swing.JTextField ToDateReceivedField;
    private javax.swing.JLabel ToDateReceivedLabel;
    private javax.swing.JLabel ToDateReceivedLabel1;
    private javax.swing.JLabel ToDateReceivedLabel2;
    private javax.swing.JComboBox<String> ToNameComboBox;
    private javax.swing.JLabel ToNameLabel;
    private javax.swing.JPanel ToPanel;
    private javax.swing.JTextField ToPeriodField;
    private javax.swing.JLabel ToPeriodLabel;
    // End of variables declaration//GEN-END:variables
}
