package Letter.Management;

import static Letter.Management.ClerkLogin.setUIFont;
import java.awt.Font;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class ClerkAddLetter extends javax.swing.JFrame {

    /**
     * Creates new form ClerkAddLetter
     */
    public ClerkAddLetter() {
        initComponents();
//        FromNameField.setVisible(false);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        HeadingPanel = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        AddLetterPanel = new javax.swing.JPanel();
        InwardRegisterNumberPanel = new javax.swing.JPanel();
        InwardRegisterNoLabel = new javax.swing.JLabel();
        InwardRegsiterNumberField = new javax.swing.JLabel();
        FromParentPanel = new javax.swing.JPanel();
        FromPanel = new javax.swing.JPanel();
        FromLetterNoLabel = new javax.swing.JLabel();
        FromLetterNoField = new javax.swing.JTextField();
        FromDateLabel = new javax.swing.JLabel();
        FromDateField = new javax.swing.JTextField();
        FromNameLabel = new javax.swing.JLabel();
        DateSentShowTodayButton = new javax.swing.JButton();
        FromNameComboBox = new javax.swing.JComboBox<>();
        FromNameField = new javax.swing.JTextField();
        SubjectPanel = new javax.swing.JPanel();
        SubjectLabel = new javax.swing.JLabel();
        SubjectField = new javax.swing.JTextField();
        ToParentPanel = new javax.swing.JPanel();
        ToPanel = new javax.swing.JPanel();
        ToNameLabel = new javax.swing.JLabel();
        ToBranchField = new javax.swing.JTextField();
        ToNameField = new javax.swing.JTextField();
        ToBranchLabel = new javax.swing.JLabel();
        ToDateReceivedLabel = new javax.swing.JLabel();
        ToDateReceivedField = new javax.swing.JTextField();
        DateReceivedShowTodayButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        AddLetterButton = new javax.swing.JButton();
        ShowRegisterButton = new javax.swing.JButton();
        EmployeeStatsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        SortByEmployeeStatsLabel = new javax.swing.JLabel();
        SortByEmployeeStatsComboBox = new javax.swing.JComboBox<>();
        FromPeriodLabel = new javax.swing.JLabel();
        FromPeriodField = new javax.swing.JTextField();
        ToPeriodLabel = new javax.swing.JLabel();
        ToPeriodField = new javax.swing.JTextField();
        BranchEmployeeStatsComboBox = new javax.swing.JComboBox<>();
        NameEmployeeStatsComboBox = new javax.swing.JComboBox<>();
        TablePanel = new javax.swing.JPanel();
        TablesPane = new javax.swing.JTabbedPane();
        ShowDirectoryScrollPane = new javax.swing.JScrollPane();
        ShowDirectoryPane = new javax.swing.JTable();
        EmployeeStatsPane = new javax.swing.JPanel();
        EmployeeStatsScrollPane = new javax.swing.JScrollPane();
        EmployeeStatsTable = new javax.swing.JTable();
        TasksScrollPane = new javax.swing.JScrollPane();
        TasksTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 640));
        setMaximumSize(new java.awt.Dimension(1000, 640));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setName("Clerk Home"); // NOI18N
        setSize(new java.awt.Dimension(1000, 640));

        HeaderPanel.setBackground(new java.awt.Color(225, 250, 225));
        HeaderPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        HeadingPanel.setBackground(new java.awt.Color(147, 217, 163));
        HeadingPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HeadingLabel.setBackground(new java.awt.Color(147, 217, 163));
        HeadingLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        HeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadingLabel.setText("INWARD REGISTER");

        javax.swing.GroupLayout HeadingPanelLayout = new javax.swing.GroupLayout(HeadingPanel);
        HeadingPanel.setLayout(HeadingPanelLayout);
        HeadingPanelLayout.setHorizontalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeadingPanelLayout.setVerticalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadingPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(HeadingLabel)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(HeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        AddLetterPanel.setBackground(new java.awt.Color(225, 250, 225));
        AddLetterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        InwardRegisterNumberPanel.setBackground(new java.awt.Color(147, 217, 163));
        InwardRegisterNumberPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        InwardRegisterNoLabel.setBackground(new java.awt.Color(102, 255, 102));
        InwardRegisterNoLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        InwardRegisterNoLabel.setText("Inward Register Number ");

        InwardRegsiterNumberField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        InwardRegsiterNumberField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InwardRegsiterNumberField.setText("01");
        InwardRegsiterNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout InwardRegisterNumberPanelLayout = new javax.swing.GroupLayout(InwardRegisterNumberPanel);
        InwardRegisterNumberPanel.setLayout(InwardRegisterNumberPanelLayout);
        InwardRegisterNumberPanelLayout.setHorizontalGroup(
            InwardRegisterNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InwardRegisterNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InwardRegisterNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InwardRegsiterNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InwardRegisterNumberPanelLayout.setVerticalGroup(
            InwardRegisterNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InwardRegisterNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InwardRegisterNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InwardRegisterNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InwardRegsiterNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        FromParentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FromPanel.setBackground(new java.awt.Color(147, 217, 163));
        FromPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "From"));

        FromLetterNoLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromLetterNoLabel.setText("Number:");
        FromLetterNoLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        FromLetterNoLabel.setMinimumSize(null);
        FromLetterNoLabel.setPreferredSize(new java.awt.Dimension(90, 26));

        FromLetterNoField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromLetterNoField.setMinimumSize(new java.awt.Dimension(110, 34));
        FromLetterNoField.setPreferredSize(new java.awt.Dimension(110, 34));

        FromDateLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromDateLabel.setText("Date:");
        FromDateLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        FromDateLabel.setMinimumSize(null);
        FromDateLabel.setPreferredSize(new java.awt.Dimension(90, 34));

        FromDateField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromDateField.setMinimumSize(new java.awt.Dimension(110, 34));
        FromDateField.setPreferredSize(new java.awt.Dimension(110, 34));

        FromNameLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromNameLabel.setText("Name:");
        FromNameLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        FromNameLabel.setMinimumSize(null);
        FromNameLabel.setPreferredSize(new java.awt.Dimension(90, 34));

        DateSentShowTodayButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        DateSentShowTodayButton.setText("Today");
        DateSentShowTodayButton.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        DateSentShowTodayButton.setMinimumSize(new java.awt.Dimension(80, 34));
        DateSentShowTodayButton.setPreferredSize(new java.awt.Dimension(80, 34));

        FromNameComboBox.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FromNameComboBox.setMinimumSize(new java.awt.Dimension(196, 32));
        FromNameComboBox.setPreferredSize(new java.awt.Dimension(196, 32));
        FromNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromNameComboBoxActionPerformed(evt);
            }
        });

        FromNameField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromNameField.setDragEnabled(true);
        FromNameField.setMargin(new java.awt.Insets(1, 1, 1, 1));
        FromNameField.setMinimumSize(new java.awt.Dimension(196, 34));
        FromNameField.setNextFocusableComponent(SubjectField);
        FromNameField.setPreferredSize(new java.awt.Dimension(196, 34));

        javax.swing.GroupLayout FromPanelLayout = new javax.swing.GroupLayout(FromPanel);
        FromPanel.setLayout(FromPanelLayout);
        FromPanelLayout.setHorizontalGroup(
            FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FromPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(FromDateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(FromLetterNoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(FromNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FromPanelLayout.createSequentialGroup()
                        .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FromPanelLayout.createSequentialGroup()
                                .addComponent(FromDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateSentShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FromLetterNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FromPanelLayout.createSequentialGroup()
                        .addComponent(FromNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FromNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        FromPanelLayout.setVerticalGroup(
            FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FromPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FromLetterNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(FromLetterNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateSentShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FromNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(FromNameComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(FromNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout FromParentPanelLayout = new javax.swing.GroupLayout(FromParentPanel);
        FromParentPanel.setLayout(FromParentPanelLayout);
        FromParentPanelLayout.setHorizontalGroup(
            FromParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FromParentPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(FromPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FromParentPanelLayout.setVerticalGroup(
            FromParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FromPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SubjectPanel.setBackground(new java.awt.Color(147, 217, 163));
        SubjectPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SubjectPanel.setMinimumSize(new java.awt.Dimension(340, 48));
        SubjectPanel.setPreferredSize(new java.awt.Dimension(340, 48));

        SubjectLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        SubjectLabel.setText("Subject");

        SubjectField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        javax.swing.GroupLayout SubjectPanelLayout = new javax.swing.GroupLayout(SubjectPanel);
        SubjectPanel.setLayout(SubjectPanelLayout);
        SubjectPanelLayout.setHorizontalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubjectPanelLayout.setVerticalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubjectPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubjectField)
                    .addComponent(SubjectLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ToParentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ToPanel.setBackground(new java.awt.Color(147, 217, 163));
        ToPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "To"));

        ToNameLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToNameLabel.setText("Name");
        ToNameLabel.setMinimumSize(new java.awt.Dimension(100, 26));
        ToNameLabel.setPreferredSize(new java.awt.Dimension(100, 26));

        ToBranchField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToBranchField.setMinimumSize(new java.awt.Dimension(150, 26));
        ToBranchField.setName(""); // NOI18N
        ToBranchField.setPreferredSize(new java.awt.Dimension(150, 26));

        ToNameField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToNameField.setMinimumSize(new java.awt.Dimension(150, 26));
        ToNameField.setName(""); // NOI18N
        ToNameField.setPreferredSize(new java.awt.Dimension(150, 26));

        ToBranchLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToBranchLabel.setText("Branch");
        ToBranchLabel.setMinimumSize(new java.awt.Dimension(100, 26));
        ToBranchLabel.setPreferredSize(new java.awt.Dimension(100, 26));

        ToDateReceivedLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToDateReceivedLabel.setText("Date Received");
        ToDateReceivedLabel.setMaximumSize(new java.awt.Dimension(100, 262626));
        ToDateReceivedLabel.setMinimumSize(new java.awt.Dimension(100, 26));
        ToDateReceivedLabel.setPreferredSize(new java.awt.Dimension(100, 26));

        ToDateReceivedField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToDateReceivedField.setMinimumSize(new java.awt.Dimension(150, 26));
        ToDateReceivedField.setName(""); // NOI18N
        ToDateReceivedField.setPreferredSize(new java.awt.Dimension(150, 26));
        ToDateReceivedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToDateReceivedFieldActionPerformed(evt);
            }
        });

        DateReceivedShowTodayButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        DateReceivedShowTodayButton.setText("Today");
        DateReceivedShowTodayButton.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        DateReceivedShowTodayButton.setMinimumSize(new java.awt.Dimension(107, 26));
        DateReceivedShowTodayButton.setPreferredSize(new java.awt.Dimension(107, 26));

        javax.swing.GroupLayout ToPanelLayout = new javax.swing.GroupLayout(ToPanel);
        ToPanel.setLayout(ToPanelLayout);
        ToPanelLayout.setHorizontalGroup(
            ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ToNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(ToDateReceivedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToBranchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToBranchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ToPanelLayout.createSequentialGroup()
                        .addComponent(ToDateReceivedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DateReceivedShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ToNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ToPanelLayout.setVerticalGroup(
            ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToDateReceivedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToDateReceivedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateReceivedShowTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToBranchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToBranchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout ToParentPanelLayout = new javax.swing.GroupLayout(ToParentPanel);
        ToParentPanel.setLayout(ToParentPanelLayout);
        ToParentPanelLayout.setHorizontalGroup(
            ToParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ToParentPanelLayout.setVerticalGroup(
            ToParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToParentPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ToPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        BackButton.setBackground(new java.awt.Color(255, 102, 102));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-src/back-arrow.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        AddLetterButton.setBackground(new java.awt.Color(102, 255, 102));
        AddLetterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-src/Add24.png"))); // NOI18N
        AddLetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLetterButtonActionPerformed(evt);
            }
        });

        ShowRegisterButton.setBackground(new java.awt.Color(255, 255, 153));
        ShowRegisterButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ShowRegisterButton.setText("Show Register");
        ShowRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRegisterButtonActionPerformed(evt);
            }
        });

        EmployeeStatsButton.setBackground(new java.awt.Color(153, 153, 255));
        EmployeeStatsButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        EmployeeStatsButton.setText("Employee Stats");
        EmployeeStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeStatsButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setText("Sort by");

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SortByEmployeeStatsLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        SortByEmployeeStatsLabel.setText("Sort by");

        SortByEmployeeStatsComboBox.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        SortByEmployeeStatsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FromPeriodLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromPeriodLabel.setText("From");

        FromPeriodField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FromPeriodField.setMinimumSize(new java.awt.Dimension(110, 34));
        FromPeriodField.setPreferredSize(new java.awt.Dimension(110, 34));

        ToPeriodLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToPeriodLabel.setText("To");

        ToPeriodField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ToPeriodField.setMinimumSize(new java.awt.Dimension(110, 34));
        ToPeriodField.setPreferredSize(new java.awt.Dimension(110, 34));

        BranchEmployeeStatsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        NameEmployeeStatsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout AddLetterPanelLayout = new javax.swing.GroupLayout(AddLetterPanel);
        AddLetterPanel.setLayout(AddLetterPanelLayout);
        AddLetterPanelLayout.setHorizontalGroup(
            AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLetterPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLetterPanelLayout.createSequentialGroup()
                        .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ToParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FromParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                            .addComponent(InwardRegisterNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(AddLetterPanelLayout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddLetterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(AddLetterPanelLayout.createSequentialGroup()
                        .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddLetterPanelLayout.createSequentialGroup()
                                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ShowRegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmployeeStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddLetterPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AddLetterPanelLayout.createSequentialGroup()
                                        .addComponent(BranchEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NameEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(AddLetterPanelLayout.createSequentialGroup()
                                .addComponent(SortByEmployeeStatsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SortByEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FromPeriodLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FromPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ToPeriodLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(59, Short.MAX_VALUE))))
        );
        AddLetterPanelLayout.setVerticalGroup(
            AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLetterPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(InwardRegisterNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FromParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddLetterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(18, 18, 18)
                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmployeeStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddLetterPanelLayout.createSequentialGroup()
                        .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BranchEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(AddLetterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SortByEmployeeStatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SortByEmployeeStatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromPeriodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToPeriodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablePanel.setBackground(new java.awt.Color(225, 250, 225));
        TablePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablesPane.setBackground(new java.awt.Color(147, 217, 163));
        TablesPane.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        TablesPane.setOpaque(true);

        ShowDirectoryPane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Inward Register", "From - Number", "From - Date", "From - Name", "Subject", "To - Date", "To - Branch", "To - Name"
            }
        ));
        ShowDirectoryScrollPane.setViewportView(ShowDirectoryPane);

        TablesPane.addTab("Show Directory", ShowDirectoryScrollPane);

        EmployeeStatsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        EmployeeStatsScrollPane.setViewportView(EmployeeStatsTable);

        TasksTable.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        TasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Total Letters", "Pending Letters", "Completed Letters"
            }
        ));
        TasksScrollPane.setViewportView(TasksTable);

        javax.swing.GroupLayout EmployeeStatsPaneLayout = new javax.swing.GroupLayout(EmployeeStatsPane);
        EmployeeStatsPane.setLayout(EmployeeStatsPaneLayout);
        EmployeeStatsPaneLayout.setHorizontalGroup(
            EmployeeStatsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeStatsPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(EmployeeStatsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeStatsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(TasksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        EmployeeStatsPaneLayout.setVerticalGroup(
            EmployeeStatsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeStatsPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(EmployeeStatsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TasksScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        TablesPane.addTab("Employee Stats", EmployeeStatsPane);

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(TablesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TablesPane)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddLetterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddLetterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddLetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLetterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddLetterButtonActionPerformed

    private void ToDateReceivedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToDateReceivedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToDateReceivedFieldActionPerformed

    private void ShowRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRegisterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowRegisterButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void EmployeeStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeStatsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeStatsButtonActionPerformed

    private void FromNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromNameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromNameComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void init() {
        setExtendedState(MAXIMIZED_BOTH);
        setUIFont (new javax.swing.plaf.FontUIResource("SansSerif",Font.PLAIN,12));
        
        URL iconURL = getClass().getResource("/img-src/logo.png");
        // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
        setTitle("Water Resources Department, Government of Maharashtra, India");
                
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkAddLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkAddLetter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLetterButton;
    private javax.swing.JPanel AddLetterPanel;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> BranchEmployeeStatsComboBox;
    private javax.swing.JButton DateReceivedShowTodayButton;
    private javax.swing.JButton DateSentShowTodayButton;
    private javax.swing.JButton EmployeeStatsButton;
    private javax.swing.JPanel EmployeeStatsPane;
    private javax.swing.JScrollPane EmployeeStatsScrollPane;
    private javax.swing.JTable EmployeeStatsTable;
    private javax.swing.JTextField FromDateField;
    private javax.swing.JLabel FromDateLabel;
    private javax.swing.JTextField FromLetterNoField;
    private javax.swing.JLabel FromLetterNoLabel;
    private javax.swing.JComboBox<String> FromNameComboBox;
    private javax.swing.JTextField FromNameField;
    private javax.swing.JLabel FromNameLabel;
    private javax.swing.JPanel FromPanel;
    private javax.swing.JPanel FromParentPanel;
    private javax.swing.JTextField FromPeriodField;
    private javax.swing.JLabel FromPeriodLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JPanel HeadingPanel;
    private javax.swing.JLabel InwardRegisterNoLabel;
    private javax.swing.JPanel InwardRegisterNumberPanel;
    private javax.swing.JLabel InwardRegsiterNumberField;
    private javax.swing.JComboBox<String> NameEmployeeStatsComboBox;
    private javax.swing.JTable ShowDirectoryPane;
    private javax.swing.JScrollPane ShowDirectoryScrollPane;
    private javax.swing.JButton ShowRegisterButton;
    private javax.swing.JComboBox<String> SortByEmployeeStatsComboBox;
    private javax.swing.JLabel SortByEmployeeStatsLabel;
    private javax.swing.JTextField SubjectField;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JPanel SubjectPanel;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JTabbedPane TablesPane;
    private javax.swing.JScrollPane TasksScrollPane;
    private javax.swing.JTable TasksTable;
    private javax.swing.JTextField ToBranchField;
    private javax.swing.JLabel ToBranchLabel;
    private javax.swing.JTextField ToDateReceivedField;
    private javax.swing.JLabel ToDateReceivedLabel;
    private javax.swing.JTextField ToNameField;
    private javax.swing.JLabel ToNameLabel;
    private javax.swing.JPanel ToPanel;
    private javax.swing.JPanel ToParentPanel;
    private javax.swing.JTextField ToPeriodField;
    private javax.swing.JLabel ToPeriodLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
