package tb;

public class ClerkHome extends javax.swing.JFrame {

    /**
     * Creates new form ClerkHome
     */
    public ClerkHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClerkHomePanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        ClerkHomeSeparator = new javax.swing.JSeparator();
        AddToDirectoryButton = new javax.swing.JButton();
        ViewDirectoryButton = new javax.swing.JButton();
        ViewEmployeeButton = new javax.swing.JButton();
        SignOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clerk Home");
        setBounds(new java.awt.Rectangle(300, 150, 700, 500));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setName("ClerkHomeFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        ClerkHomePanel.setBackground(new java.awt.Color(232, 246, 239));
        ClerkHomePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        WelcomeLabel.setBackground(new java.awt.Color(204, 204, 204));
        WelcomeLabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(0, 102, 153));
        WelcomeLabel.setText("WELCOME");
        WelcomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ClerkHomeSeparator.setForeground(new java.awt.Color(0, 153, 153));
        ClerkHomeSeparator.setToolTipText("");

        AddToDirectoryButton.setBackground(new java.awt.Color(0, 102, 153));
        AddToDirectoryButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddToDirectoryButton.setForeground(new java.awt.Color(255, 255, 255));
        AddToDirectoryButton.setText("Add To Directory");
        AddToDirectoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddToDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToDirectoryActionPerformed(evt);
            }
        });

        ViewDirectoryButton.setBackground(new java.awt.Color(0, 102, 153));
        ViewDirectoryButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ViewDirectoryButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewDirectoryButton.setText("View Directory");
        ViewDirectoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ViewDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDirectoryButtonActionPerformed(evt);
            }
        });

        ViewEmployeeButton.setBackground(new java.awt.Color(0, 102, 153));
        ViewEmployeeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ViewEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewEmployeeButton.setText("View Employees");
        ViewEmployeeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ViewEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmployeeButtonActionPerformed(evt);
            }
        });

        SignOutButton.setBackground(new java.awt.Color(255, 51, 51));
        SignOutButton.setForeground(new java.awt.Color(255, 255, 255));
        SignOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-src/logo-white.png"))); // NOI18N
        SignOutButton.setToolTipText("बाहेर पडावे ");
        SignOutButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClerkHomePanelLayout = new javax.swing.GroupLayout(ClerkHomePanel);
        ClerkHomePanel.setLayout(ClerkHomePanelLayout);
        ClerkHomePanelLayout.setHorizontalGroup(
            ClerkHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClerkHomePanelLayout.createSequentialGroup()
                .addGroup(ClerkHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClerkHomePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(SignOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClerkHomePanelLayout.createSequentialGroup()
                        .addContainerGap(122, Short.MAX_VALUE)
                        .addComponent(ClerkHomeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(ClerkHomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ClerkHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClerkHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ViewEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddToDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(WelcomeLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClerkHomePanelLayout.setVerticalGroup(
            ClerkHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClerkHomePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(WelcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(ClerkHomeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(AddToDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ViewDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ViewEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(SignOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClerkHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClerkHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ClerkHomePanel.getAccessibleContext().setAccessibleName("ClerkHomePanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToDirectoryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);  
        new ClerkAddToDirectory().setVisible(true);
    }//GEN-LAST:event_AddToDirectoryActionPerformed

    private void ViewDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDirectoryButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);  
        new ClerkViewDirectory().setVisible(true);
    }//GEN-LAST:event_ViewDirectoryButtonActionPerformed

    private void ViewEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmployeeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);  
        new ClerkEmployeeStats().setVisible(true);
    }//GEN-LAST:event_ViewEmployeeButtonActionPerformed

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);  
        new ClerkLogin().setVisible(true);
    }//GEN-LAST:event_SignOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToDirectoryButton;
    private javax.swing.JPanel ClerkHomePanel;
    private javax.swing.JSeparator ClerkHomeSeparator;
    private javax.swing.JButton SignOutButton;
    private javax.swing.JButton ViewDirectoryButton;
    private javax.swing.JButton ViewEmployeeButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
